name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: registry.access.redhat.com/ubi9-minimal
    steps:
      - name: Install dependencies
        run: microdnf -y install maven rpm tar
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Maven build
        run: mvn -B clean package
