name: Continuous Integration
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/mizdebsk/maven:latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Maven build
        run: mvn -B clean package
